[package]
name = "dnsraw"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "dnsraw"
path = "src/main.rs"

[lib]
path = "src/lib.rs"


[profile.release]
strip = true  # Automatically strip symbols from the binary.
lto = true
opt-level = "z"  # Optimize for size.
codegen-units = 1


[dependencies]
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
hickory-proto = "0.25.2"
hickory-resolver = "0.25.2"
tokio = {version = "1.48.0", features = ["full"]}
lazy_static = "1.5.0"
