[package]
name = "dnsraw"
version = "0.1.0"
edition = "2024"

[dependencies]
dns-parser = "0.8.0"
hickory-proto = "0.25.2"
hickory-resolver = "0.25.2"
tokio = {version = "1.48.0", features = ["full"]}
trust-dns-resolver = "0.23.2"
